#!/bin/bash 

JBOSS_HOME=/opt/jboss-eap-6.2
JBOSS_BIN_DIR=${JBOSS_HOME}/bin
JBOSS_PID_FILE=${JBOSS_HOME}/jboss.pid
JBOSS_CLI=$JBOSS_BIN_DIR/jboss-cli.sh

function start() {
	mkdir -p /jboss-prepare

	echo "Starting JBoss EAP..."

	${JBOSS_BIN_DIR}/standalone.sh > /jboss-prepare/start.log 2>&1 &

  count=0
  while [ ${count} -lt 64 ]
  do
    res=`$JBOSS_CLI -c ":read-attribute(name=server-state)" 2>&1 || :`

    if [[ $res =~ '"result" => "running"' ]]; then
      echo "JBoss EAP is running"
      return 0
    fi

    let count+=1
    sleep 2
  done

  echo "JBoss EAP failed to launch"
  exit 1
}

function stop() {
  res=`$JBOSS_CLI -c ":shutdown" 2>&1 || :`

  if [[ $res =~ '"outcome" => "success"' ]]; then
    echo "EAP is stopped"
    return 0
  fi

  echo "EAP failed to stop"
  return 1
}

function deploy() {
  echo "Deploying artifact $1..."
  res=`$JBOSS_CLI -c "deploy $1" 2>&1 || :`

  if [[ $res =~ '"outcome" => "success"' ]]; then
    echo "EAP is stopped"
    return 0
  fi

  echo "Failed to deploy artifact $1"
  return 1
}

local_source_dir=/eap-source
mkdir -p $local_source_dir
cp -ad /usr/src/* $local_source_dir

if [ -f /eap-source/pom.xml ]; then
	pushd /eap-source
	mvn package

	if [ $? -ne 0 ]; then
		exit $?
	fi

	popd
else
	echo "Artifact deployment not implemented yet"
	exit -1
fi

# copy war into deployment dir
# start jboss (launch.sh)
# wait for deployment scanner to run
# stop jboss
artifact=/eap-source/deployments/ROOT.war

start
deploy $artifact
stop
