#!/bin/bash 

function restore_saved_artifacts() {
  if [ -f /usr/artifacts/maven.tar.gz ]; then
    echo "Restoring saved artifacts from prior build"
    pushd /
    tar zxvf /usr/artifacts/maven.tar.gz
    popd
  fi
}

local_source_dir=/eap-source
artifact_dir=/artifacts

mkdir -p $local_source_dir
mkdir -p $artifact_dir

cp -ad /usr/src/* $local_source_dir

if [ -f "$local_source_dir/pom.xml" ]; then
  restore_saved_artifacts
  pushd $local_source_dir
  mvn package

  if [ $? -ne 0 ]; then
    exit $?
  fi

  cp target/*.war $artifact_dir/

  popd
else
  echo -n "Copying binaries in source directory into /artifacts for later deployment..."
  cp $local_source_dir/*.war $artifact_dir/
  echo "...done"
fi

